ci/di

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -27,6 +27,16 @@ jobs:
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
 
+      - name: Build with Gradle
+        run: ./gradlew build --refresh-dependencies --info
+
+      - name: Verify JAR file exists
+        run: |
+          if [ ! -f build/libs/config-1.0.0.jar ]; then
+            echo "JAR file not found!"
+            exit 1
+          fi
+
       - name: Install Docker Compose
         run: |
           sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K.*?(?=")')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
@@ -40,9 +50,6 @@ jobs:
 
       - name: Publish exception-handling-starter to Maven Local
         run: ./gradlew :exception-handling-starter:publishToMavenLocal
-
-      - name: Build with Gradle
-        run: ./gradlew build --refresh-dependencies --info
 
       - name: Run tests
         run: ./gradlew test --info
